name: SaveDynamicShop
version: 1.0.0
main: net.valdemarf.savedynamicshop.SaveDynamicShop
api-version: 1.18
authors: [ValdemarF]

depend: [ProtocolLib, Vault]

permissions:
  saverotatingshop.admin:
    default: op
